[2024-04-16T00:00:08.710+0000] {processor.py:161} INFO - Started process (PID=609) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:00:08.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:00:08.716+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:00:08.715+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:00:08.761+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:00:08.763+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:00:08.764+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:00:08.785+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:00:08.861+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:00:08.861+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:00:08.920+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:00:08.919+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-16T00:00:08.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.280 seconds
[2024-04-16T00:00:39.243+0000] {processor.py:161} INFO - Started process (PID=619) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:00:39.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:00:39.246+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:00:39.246+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:00:39.285+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:00:39.286+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:00:39.287+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:00:39.303+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:00:39.346+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:00:39.345+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:00:39.389+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:00:39.389+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-16T00:00:39.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.204 seconds
[2024-04-16T00:01:09.582+0000] {processor.py:161} INFO - Started process (PID=629) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:01:09.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:01:09.587+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:01:09.586+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:01:09.640+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:01:09.641+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:01:09.643+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:01:09.679+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:01:09.776+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:01:09.775+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:01:09.908+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:01:09.907+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-16T00:01:10.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.473 seconds
[2024-04-16T00:01:40.729+0000] {processor.py:161} INFO - Started process (PID=644) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:01:40.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:01:40.733+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:01:40.732+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:01:40.765+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:01:40.766+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:01:40.766+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:01:40.782+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:01:40.849+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:01:40.848+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:01:40.903+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:01:40.903+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-16T00:01:40.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.225 seconds
[2024-04-16T00:02:11.319+0000] {processor.py:161} INFO - Started process (PID=654) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:02:11.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:02:11.333+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:02:11.332+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:02:11.377+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:02:11.378+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:02:11.380+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:02:11.408+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:02:11.508+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:02:11.507+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:02:11.667+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:02:11.667+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-16T00:02:11.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.445 seconds
[2024-04-16T00:02:42.458+0000] {processor.py:161} INFO - Started process (PID=666) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:02:42.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:02:42.463+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:02:42.463+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:02:42.501+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:02:42.502+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:02:42.503+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:02:42.521+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:02:42.565+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:02:42.565+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:02:42.605+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:02:42.604+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-16T00:02:42.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.198 seconds
[2024-04-16T00:03:13.984+0000] {processor.py:161} INFO - Started process (PID=676) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:03:13.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:03:14.038+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:03:14.007+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:03:14.672+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:03:14.681+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:03:14.685+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:03:14.775+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:03:15.110+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:03:15.110+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:03:15.376+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:03:15.375+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-16T00:03:15.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.837 seconds
[2024-04-16T00:03:46.234+0000] {processor.py:161} INFO - Started process (PID=686) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:03:46.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:03:46.238+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:03:46.237+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:03:46.265+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:03:46.266+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:03:46.267+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:03:46.282+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:03:46.323+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:03:46.323+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:03:46.359+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:03:46.359+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-16T00:03:46.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.184 seconds
[2024-04-16T00:04:16.596+0000] {processor.py:161} INFO - Started process (PID=696) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:04:16.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:04:16.600+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:04:16.599+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:04:16.629+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:04:16.630+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:04:16.631+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:04:16.648+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:04:16.689+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:04:16.689+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:04:16.724+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:04:16.724+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-16T00:04:16.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.181 seconds
[2024-04-16T00:04:46.893+0000] {processor.py:161} INFO - Started process (PID=706) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:04:46.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:04:46.897+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:04:46.896+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:04:46.925+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:04:46.926+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:04:46.927+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:04:46.942+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:04:46.983+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:04:46.983+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:04:47.021+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:04:47.021+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-16T00:04:47.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.184 seconds
[2024-04-16T00:05:17.799+0000] {processor.py:161} INFO - Started process (PID=715) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:05:17.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:05:17.802+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:05:17.802+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:05:17.833+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:05:17.834+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:05:17.835+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:05:17.855+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:05:17.895+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:05:17.894+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:05:17.933+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:05:17.933+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-16T00:05:17.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.179 seconds
[2024-04-16T00:05:48.210+0000] {processor.py:161} INFO - Started process (PID=726) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:05:48.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:05:48.220+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:05:48.219+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:05:48.295+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:05:48.301+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:05:48.303+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:05:48.348+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:05:48.671+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:05:48.671+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:05:48.712+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:05:48.712+0000] {dag.py:3118} INFO - Creating ORM DAG for m_dag_ejecut.
[2024-04-16T00:05:48.824+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:05:48.823+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:05:49.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.867 seconds
[2024-04-16T00:06:19.603+0000] {processor.py:161} INFO - Started process (PID=738) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:06:19.624+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:06:19.627+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:06:19.626+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:06:19.679+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:06:19.680+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:06:19.681+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:06:19.709+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:06:19.971+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:06:19.971+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:06:19.991+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:06:19.991+0000] {dag.py:3118} INFO - Creating ORM DAG for m_dag_ejecut.
[2024-04-16T00:06:20.013+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:06:20.013+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:06:20.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.476 seconds
[2024-04-16T00:06:50.394+0000] {processor.py:161} INFO - Started process (PID=746) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:06:50.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:06:50.399+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:06:50.398+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:06:50.453+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:06:50.454+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:06:50.456+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:06:50.478+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:06:50.548+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:06:50.547+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:06:50.607+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:06:50.607+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:06:50.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.312 seconds
[2024-04-16T00:07:21.309+0000] {processor.py:161} INFO - Started process (PID=756) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:07:21.330+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:07:21.382+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:07:21.381+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:07:21.503+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:07:21.508+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:07:21.509+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:07:21.530+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:07:21.639+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:07:21.638+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:07:21.725+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:07:21.725+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:07:24.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 3.718 seconds
[2024-04-16T00:07:55.541+0000] {processor.py:161} INFO - Started process (PID=766) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:07:55.549+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:07:55.551+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:07:55.550+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:07:55.594+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:07:55.595+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:07:55.596+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:07:55.627+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:07:55.682+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:07:55.682+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:07:55.744+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:07:55.743+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:07:55.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.282 seconds
[2024-04-16T00:08:26.368+0000] {processor.py:161} INFO - Started process (PID=777) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:08:26.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:08:26.371+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:08:26.371+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:08:26.402+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:08:26.403+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:08:26.404+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:08:26.421+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:08:26.473+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:08:26.472+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:08:26.524+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:08:26.523+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:08:26.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.265 seconds
[2024-04-16T00:08:56.831+0000] {processor.py:161} INFO - Started process (PID=786) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:08:56.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:08:56.838+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:08:56.837+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:08:56.972+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:08:56.983+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:08:56.986+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:08:57.012+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:08:57.060+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:08:57.059+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:08:57.123+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:08:57.122+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:08:57.159+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.343 seconds
[2024-04-16T00:09:27.951+0000] {processor.py:161} INFO - Started process (PID=796) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:09:27.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:09:27.955+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:09:27.954+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:09:28.002+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:09:28.004+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:09:28.004+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:09:28.030+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:09:28.092+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:09:28.092+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:09:28.180+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:09:28.179+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:09:28.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.295 seconds
[2024-04-16T00:09:59.095+0000] {processor.py:161} INFO - Started process (PID=806) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:09:59.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:09:59.101+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:09:59.099+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:09:59.130+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:09:59.130+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:09:59.131+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:09:59.144+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:09:59.182+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:09:59.181+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:09:59.278+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:09:59.277+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:10:00.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.864 seconds
[2024-04-16T00:10:31.583+0000] {processor.py:161} INFO - Started process (PID=817) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:10:31.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:10:31.586+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:10:31.585+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:10:31.611+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:10:31.612+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:10:31.613+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:10:31.625+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:10:31.665+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:10:31.664+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:10:31.698+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:10:31.698+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:10:31.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.343 seconds
[2024-04-16T00:11:02.527+0000] {processor.py:161} INFO - Started process (PID=827) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:11:02.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:11:02.534+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:11:02.533+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:11:02.865+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:11:02.867+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:11:02.872+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:11:02.897+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:11:03.039+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:11:03.038+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:11:03.186+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:11:03.186+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:11:03.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.845 seconds
[2024-04-16T00:13:29.130+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:13:29.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:13:29.619+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:13:29.509+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:13:29.966+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:13:29.968+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:13:29.969+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:13:30.442+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:13:35.942+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:13:35.941+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:13:36.509+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:13:36.509+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:13:37.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 8.888 seconds
[2024-04-16T00:14:08.433+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:14:08.436+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:14:08.440+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:14:08.439+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:14:08.477+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:14:08.478+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:14:08.479+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:14:08.496+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:14:09.700+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:14:09.699+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:14:09.901+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:14:09.900+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:14:11.555+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 3.136 seconds
[2024-04-16T00:14:43.025+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:14:43.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:14:43.043+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:14:43.042+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:14:43.102+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:14:43.105+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:14:43.106+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:14:43.126+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:14:43.198+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:14:43.196+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:14:43.265+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:14:43.264+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:14:45.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.926 seconds
[2024-04-16T00:19:04.545+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:19:04.550+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:19:04.562+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:19:04.561+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:19:04.633+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:19:04.634+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:19:04.635+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:19:04.678+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:19:06.009+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:19:06.008+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:19:06.113+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:19:06.112+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:19:06.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.691 seconds
[2024-04-16T00:19:37.196+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:19:37.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:19:37.284+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:19:37.283+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:19:38.135+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:19:38.148+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:19:38.164+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:19:38.346+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:19:38.918+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:19:38.917+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:19:39.351+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:19:39.350+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:19:53.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 16.663 seconds
[2024-04-16T00:20:25.276+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:20:25.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:20:25.544+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:20:25.543+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:20:25.878+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:20:25.879+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:20:25.880+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:20:25.912+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:20:25.952+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:20:25.951+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:20:25.986+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:20:25.985+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:20:27.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.524 seconds
[2024-04-16T00:20:58.446+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:20:58.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:20:58.457+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:20:58.456+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:20:58.739+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:20:58.740+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:20:58.741+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:20:58.786+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:20:58.965+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:20:58.964+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:20:59.103+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:20:59.102+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:20:59.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.542 seconds
[2024-04-16T00:21:35.666+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:21:35.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:21:35.779+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:21:35.779+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:21:36.791+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:21:36.802+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:21:36.803+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:21:37.029+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:21:37.211+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:21:37.211+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:21:37.440+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:21:37.440+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:21:39.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 4.313 seconds
[2024-04-16T00:22:13.137+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:22:13.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:22:13.217+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:22:13.217+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:22:14.735+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:22:14.765+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:22:14.782+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:22:15.032+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:22:15.397+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:22:15.397+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:22:16.809+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:22:16.808+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:22:18.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 4.994 seconds
[2024-04-16T00:22:50.099+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:22:50.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:22:50.144+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:22:50.143+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:22:50.772+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:22:50.781+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:22:50.782+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:22:50.806+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:22:50.878+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:22:50.878+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:22:51.150+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:22:51.138+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:22:53.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 3.554 seconds
[2024-04-16T00:23:24.531+0000] {processor.py:161} INFO - Started process (PID=140) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:23:24.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:23:24.540+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:23:24.539+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:23:24.664+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:23:24.671+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:23:24.672+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:23:24.692+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:23:24.781+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:23:24.780+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:23:24.840+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:23:24.840+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:23:25.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.506 seconds
[2024-04-16T00:23:55.436+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:23:55.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:23:55.443+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:23:55.442+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:23:55.471+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:23:55.472+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:23:55.472+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:23:55.484+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:23:55.544+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:23:55.544+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:23:55.645+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:23:55.644+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:23:58.265+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.848 seconds
[2024-04-16T00:24:29.821+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:24:29.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:24:29.845+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:24:29.842+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:24:29.963+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:24:29.965+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:24:29.971+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:24:29.993+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:24:30.048+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:24:30.047+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:24:30.091+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:24:30.091+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:24:32.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.544 seconds
[2024-04-16T00:25:02.622+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:25:02.624+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:25:02.628+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:25:02.627+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:25:02.657+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:25:02.658+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:25:02.659+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:25:02.677+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:25:02.719+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:25:02.719+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:25:02.780+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:25:02.780+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:25:02.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.204 seconds
[2024-04-16T00:25:33.134+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:25:33.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:25:33.139+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:25:33.138+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:25:33.168+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:25:33.169+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:25:33.169+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:25:33.183+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:25:33.227+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:25:33.227+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:25:33.277+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:25:33.277+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:25:33.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.223 seconds
[2024-04-16T00:26:03.879+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:26:03.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:26:03.906+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:26:03.905+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:26:04.026+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:26:04.031+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:26:04.032+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:26:04.068+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:26:04.167+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:26:04.166+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:26:04.314+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:26:04.314+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:26:04.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.756 seconds
[2024-04-16T00:26:35.081+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:26:35.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:26:35.087+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:26:35.086+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:26:35.135+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:26:35.136+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:26:35.137+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:26:35.176+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:26:35.246+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:26:35.245+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:26:35.297+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:26:35.297+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:26:35.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.291 seconds
[2024-04-16T00:27:05.500+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:27:05.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:27:05.505+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:27:05.505+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:27:05.533+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:27:05.533+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:27:05.534+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:27:05.546+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:27:05.583+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:27:05.583+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:27:05.614+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:27:05.614+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:27:05.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.154 seconds
[2024-04-16T00:27:35.759+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:27:35.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:27:35.776+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:27:35.775+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:27:35.807+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:27:35.807+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:27:35.808+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:27:35.828+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:27:35.873+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:27:35.872+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:27:35.907+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:27:35.907+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:27:35.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.193 seconds
[2024-04-16T00:28:06.045+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:28:06.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:28:06.049+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:28:06.049+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:28:06.075+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:28:06.075+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:28:06.076+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:28:06.088+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:28:06.127+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:28:06.127+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:28:06.163+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:28:06.162+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:28:06.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.163 seconds
[2024-04-16T00:28:36.502+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:28:36.503+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:28:36.507+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:28:36.506+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:28:36.534+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:28:36.535+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:28:36.536+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:28:36.550+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:28:36.616+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:28:36.615+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:28:36.681+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:28:36.680+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:28:36.732+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.242 seconds
[2024-04-16T00:29:07.202+0000] {processor.py:161} INFO - Started process (PID=252) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:29:07.204+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:29:07.219+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:29:07.219+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:29:07.277+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:29:07.278+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:29:07.279+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:29:07.312+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:29:07.389+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:29:07.388+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:29:07.481+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:29:07.480+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:29:07.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.365 seconds
[2024-04-16T00:29:37.942+0000] {processor.py:161} INFO - Started process (PID=263) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:29:37.944+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:29:37.956+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:29:37.955+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:29:38.161+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:29:38.165+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:29:38.167+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:29:38.212+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:29:38.301+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:29:38.300+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:29:38.383+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:29:38.382+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:29:38.411+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.493 seconds
[2024-04-16T00:30:08.902+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:30:08.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:30:08.919+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:30:08.918+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:30:09.009+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:30:09.010+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:30:09.012+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:30:09.077+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:30:09.212+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:30:09.212+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:30:09.304+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:30:09.303+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:30:09.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.810 seconds
[2024-04-16T00:30:40.229+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:30:40.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:30:40.234+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:30:40.233+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:30:40.291+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:30:40.292+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:30:40.293+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:30:40.311+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:30:40.397+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:30:40.396+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:30:40.464+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:30:40.463+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:30:40.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.405 seconds
[2024-04-16T00:31:11.234+0000] {processor.py:161} INFO - Started process (PID=293) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:31:11.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:31:11.240+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:31:11.239+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:31:11.276+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:31:11.277+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:31:11.277+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:31:11.294+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:31:11.354+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:31:11.353+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:31:11.417+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:31:11.416+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:31:11.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.278 seconds
[2024-04-16T00:31:47.170+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:31:47.224+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:31:47.230+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:31:47.229+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:31:48.472+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:31:48.650+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:31:48.767+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:31:48.822+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:31:49.280+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:31:49.279+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:31:53.615+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:31:53.614+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:31:58.007+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 10.861 seconds
[2024-04-16T00:32:28.814+0000] {processor.py:161} INFO - Started process (PID=318) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:32:28.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:32:28.842+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:32:28.838+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:32:29.021+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:32:29.032+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:32:29.034+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:32:29.092+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:32:29.302+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:32:29.302+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:32:29.539+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:32:29.539+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:32:29.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.113 seconds
[2024-04-16T00:33:02.017+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:33:02.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:33:02.035+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:33:02.034+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:33:02.261+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:33:02.271+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:33:02.275+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:33:02.342+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:33:02.519+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:33:02.518+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:33:02.700+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:33:02.699+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:33:03.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.693 seconds
[2024-04-16T00:33:35.402+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T00:33:35.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T00:33:35.461+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:33:35.460+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T00:33:35.841+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T00:33:35.864+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:33:35.866+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T00:33:35.922+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T00:33:36.034+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:33:36.034+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T00:33:36.087+0000] {logging_mixin.py:188} INFO - [2024-04-16T00:33:36.086+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T00:33:38.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.668 seconds
[2024-04-16T23:13:21.898+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:13:21.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:13:22.007+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:13:22.006+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:13:25.076+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:13:25.084+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:13:25.087+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:13:25.267+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:13:34.358+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:13:34.348+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:13:35.277+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:13:35.276+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:13:36.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 15.763 seconds
[2024-04-16T23:14:07.374+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:14:07.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:14:07.386+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:14:07.386+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:14:07.455+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:14:07.456+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:14:07.457+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:14:07.546+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:14:07.763+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:14:07.745+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:14:08.011+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:14:08.010+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:14:08.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.821 seconds
[2024-04-16T23:14:38.869+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:14:38.911+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:14:38.999+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:14:38.996+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:14:40.051+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:14:40.054+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:14:40.055+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:14:40.076+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:14:40.135+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:14:40.134+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:14:40.205+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:14:40.204+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:14:40.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.835 seconds
[2024-04-16T23:15:11.981+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:15:12.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:15:12.045+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:15:12.043+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:15:12.249+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:15:12.250+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:15:12.252+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:15:12.339+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:15:13.290+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:15:13.289+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:15:13.493+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:15:13.492+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:15:13.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.777 seconds
[2024-04-16T23:15:45.185+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:15:45.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:15:45.474+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:15:45.473+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:15:46.719+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:15:46.720+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:15:46.732+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:15:46.768+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:15:47.030+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:15:47.029+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:15:47.208+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:15:47.208+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:15:48.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.952 seconds
[2024-04-16T23:16:19.411+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:16:19.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:16:19.450+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:16:19.449+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:16:19.618+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:16:19.620+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:16:19.622+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:16:19.877+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:16:20.072+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:16:20.071+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:16:20.220+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:16:20.220+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:16:20.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.295 seconds
[2024-04-16T23:16:53.096+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:16:53.126+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:16:53.175+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:16:53.174+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:16:54.502+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:16:54.594+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:16:54.690+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:16:54.759+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:16:54.963+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:16:54.962+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:16:55.345+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:16:55.344+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:16:55.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.634 seconds
[2024-04-16T23:17:26.094+0000] {processor.py:161} INFO - Started process (PID=132) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:17:26.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:17:26.109+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:17:26.101+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:17:26.166+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:17:26.166+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:17:26.205+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:17:26.254+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:17:26.397+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:17:26.397+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:17:26.547+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:17:26.547+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:17:26.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.558 seconds
[2024-04-16T23:17:57.027+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:17:57.042+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:17:57.059+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:17:57.058+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:17:57.148+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:17:57.150+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:17:57.151+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:17:57.205+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:17:57.331+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:17:57.327+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:17:57.447+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:17:57.446+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:17:57.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.612 seconds
[2024-04-16T23:18:28.200+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:18:28.204+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:18:28.222+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:18:28.221+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:18:28.615+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:18:28.617+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:18:28.619+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:18:28.668+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:18:28.799+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:18:28.798+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:18:28.977+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:18:28.970+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:18:29.082+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.940 seconds
[2024-04-16T23:19:06.431+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:19:06.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:19:08.088+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:19:08.045+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:19:11.741+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:19:11.755+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:19:11.772+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:19:11.930+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:19:12.772+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:19:12.772+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:19:14.862+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:19:14.861+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:19:17.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 11.847 seconds
[2024-04-16T23:19:49.325+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:19:49.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:19:49.514+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:19:49.514+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:19:49.772+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:19:49.774+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:19:49.806+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:19:49.860+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:19:50.156+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:19:50.156+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:19:50.371+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:19:50.371+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:19:50.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.790 seconds
[2024-04-16T23:20:21.833+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:20:21.850+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:20:21.859+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:20:21.858+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:20:21.912+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:20:21.917+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:20:21.918+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:20:21.948+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:20:22.022+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:20:22.021+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:20:22.111+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:20:22.111+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:20:22.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.390 seconds
[2024-04-16T23:20:52.919+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:20:52.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:20:52.929+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:20:52.928+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:20:52.992+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:20:52.997+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:20:53.004+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:20:53.054+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:20:53.189+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:20:53.189+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:20:53.315+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:20:53.314+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:20:53.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.534 seconds
[2024-04-16T23:21:24.337+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:21:24.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:21:24.371+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:21:24.370+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-16T23:21:24.605+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-16T23:21:24.638+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:21:24.677+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-16T23:21:24.733+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-16T23:21:24.955+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:21:24.954+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T23:21:25.116+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:21:25.116+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-16T23:21:25.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.988 seconds
[2024-04-16T23:21:59.838+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/Prueba.py
[2024-04-16T23:22:00.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-16T23:22:00.341+0000] {logging_mixin.py:188} INFO - [2024-04-16T23:22:00.340+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
