[2024-04-20T13:30:45.784+0000] {processor.py:161} INFO - Started process (PID=2662) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:30:45.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:30:45.799+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:30:45.798+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:30:46.504+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:30:46.509+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:30:46.695+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:30:46.854+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:30:51.923+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:30:51.922+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:30:52.007+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:30:52.007+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:30:52.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 6.592 seconds
[2024-04-20T13:31:25.546+0000] {processor.py:161} INFO - Started process (PID=2682) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:31:25.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:31:25.599+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:31:25.598+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:31:27.274+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:31:27.361+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:31:27.453+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:31:27.541+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:31:27.802+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:31:27.801+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:31:28.031+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:31:28.031+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:31:28.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 3.128 seconds
[2024-04-20T13:32:00.604+0000] {processor.py:161} INFO - Started process (PID=2697) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:32:00.617+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:32:00.620+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:32:00.619+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:32:00.713+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:32:00.719+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:32:00.720+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:32:00.779+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:32:00.910+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:32:00.910+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:32:01.067+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:32:01.066+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:32:01.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.653 seconds
[2024-04-20T13:32:35.536+0000] {processor.py:161} INFO - Started process (PID=2711) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:32:35.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:32:35.568+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:32:35.567+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:32:35.840+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:32:35.847+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:32:35.859+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:32:35.988+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:32:36.341+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:32:36.340+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:32:36.579+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:32:36.578+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:32:36.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.235 seconds
[2024-04-20T13:33:12.139+0000] {processor.py:161} INFO - Started process (PID=2724) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:33:12.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:33:12.172+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:33:12.171+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:33:12.481+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:33:12.487+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:33:12.488+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:33:12.545+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:33:12.724+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:33:12.713+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:33:12.873+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:33:12.862+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:33:13.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.065 seconds
[2024-04-20T13:33:50.496+0000] {processor.py:161} INFO - Started process (PID=2739) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:33:50.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:33:50.500+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:33:50.500+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:33:50.541+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:33:50.543+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:33:50.546+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:33:50.588+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:33:50.651+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:33:50.651+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:33:50.702+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:33:50.702+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:33:51.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.499 seconds
[2024-04-20T13:34:22.599+0000] {processor.py:161} INFO - Started process (PID=2754) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:34:22.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:34:22.634+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:34:22.633+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:34:23.010+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:34:23.022+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:34:23.027+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:34:23.104+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:34:23.277+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:34:23.276+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:34:23.435+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:34:23.434+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:34:23.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.221 seconds
[2024-04-20T13:34:55.191+0000] {processor.py:161} INFO - Started process (PID=2774) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:34:55.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:34:55.207+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:34:55.206+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:34:55.265+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:34:55.267+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:34:55.268+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:34:55.327+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:34:55.471+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:34:55.470+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:34:55.670+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:34:55.669+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:34:55.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.685 seconds
[2024-04-20T13:35:32.552+0000] {processor.py:161} INFO - Started process (PID=2788) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:35:32.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:35:32.561+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:35:32.560+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:35:32.621+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:35:32.623+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:35:32.625+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:35:32.688+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:35:32.813+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:35:32.812+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:35:32.957+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:35:32.956+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:35:33.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.530 seconds
[2024-04-20T13:36:03.416+0000] {processor.py:161} INFO - Started process (PID=2799) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:36:03.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:36:03.421+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:36:03.419+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:36:03.448+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:36:03.449+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:36:03.449+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:36:03.465+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:36:03.718+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:36:03.717+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:36:03.764+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:36:03.764+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:36:05.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.120 seconds
[2024-04-20T13:36:36.341+0000] {processor.py:161} INFO - Started process (PID=2813) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:36:36.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:36:36.345+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:36:36.344+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:36:36.379+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:36:36.380+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:36:36.381+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:36:36.409+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:36:36.469+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:36:36.468+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:36:36.540+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:36:36.539+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:36:36.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.281 seconds
[2024-04-20T13:37:06.704+0000] {processor.py:161} INFO - Started process (PID=2826) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:37:11.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:37:11.144+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:37:11.144+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:37:11.177+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:37:11.178+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:37:11.179+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:37:11.201+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:37:12.194+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:37:12.194+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:37:12.241+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:37:12.241+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:37:13.897+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 7.201 seconds
[2024-04-20T13:37:44.733+0000] {processor.py:161} INFO - Started process (PID=2841) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:37:44.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:37:44.750+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:37:44.749+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:37:45.110+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:37:45.138+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:37:45.153+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:37:45.209+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:37:45.338+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:37:45.338+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:37:45.470+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:37:45.469+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:37:45.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.994 seconds
[2024-04-20T13:38:16.308+0000] {processor.py:161} INFO - Started process (PID=2857) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:38:16.310+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:38:16.311+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:38:16.311+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:38:16.344+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:38:16.345+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:38:16.347+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:38:16.371+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:38:16.417+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:38:16.417+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:38:16.473+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:38:16.473+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:38:17.183+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.883 seconds
[2024-04-20T13:38:48.184+0000] {processor.py:161} INFO - Started process (PID=2870) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:38:48.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:38:48.194+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:38:48.193+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:38:48.239+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:38:48.247+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:38:48.248+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:38:48.289+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:38:48.418+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:38:48.417+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:38:48.578+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:38:48.577+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:38:49.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.379 seconds
[2024-04-20T13:39:19.839+0000] {processor.py:161} INFO - Started process (PID=2885) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:39:19.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:39:19.843+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:39:19.842+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:39:19.872+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:39:19.873+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:39:19.873+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:39:19.888+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:39:19.931+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:39:19.930+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:39:19.971+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:39:19.971+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:39:22.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.248 seconds
[2024-04-20T13:39:53.969+0000] {processor.py:161} INFO - Started process (PID=2899) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:39:53.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:39:53.985+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:39:53.978+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:39:54.053+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:39:54.053+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:39:54.054+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:39:54.095+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:39:54.191+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:39:54.190+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:39:55.134+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:39:54.982+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:39:57.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 3.123 seconds
[2024-04-20T13:40:27.758+0000] {processor.py:161} INFO - Started process (PID=2919) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:40:27.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:40:27.763+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:40:27.762+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:40:27.799+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:40:27.800+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:40:27.801+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:40:27.820+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:40:27.872+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:40:27.871+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:40:27.933+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:40:27.933+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:40:27.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.235 seconds
[2024-04-20T13:40:58.680+0000] {processor.py:161} INFO - Started process (PID=2933) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:40:58.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:40:58.685+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:40:58.684+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:40:58.720+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:40:58.721+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:40:58.722+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:40:58.739+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:40:58.792+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:40:58.792+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:40:58.905+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:40:58.904+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:40:59.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.450 seconds
[2024-04-20T13:41:29.530+0000] {processor.py:161} INFO - Started process (PID=2947) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:41:29.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:41:29.533+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:41:29.533+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:41:29.566+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:41:29.567+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:41:29.568+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:41:29.586+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:41:29.626+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:41:29.625+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:41:29.674+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:41:29.674+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:41:30.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.273 seconds
[2024-04-20T13:42:01.283+0000] {processor.py:161} INFO - Started process (PID=2961) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:42:01.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:42:01.289+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:42:01.288+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:42:01.324+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:42:01.325+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:42:01.325+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:42:01.343+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:42:01.416+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:42:01.415+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:42:01.492+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:42:01.492+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:42:01.587+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.321 seconds
[2024-04-20T13:43:10.585+0000] {processor.py:161} INFO - Started process (PID=2979) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:43:10.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:43:10.591+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:43:10.591+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:43:10.648+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:43:10.649+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:43:10.650+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:43:10.677+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:43:10.744+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:43:10.743+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:43:10.843+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:43:10.843+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:43:10.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.400 seconds
[2024-04-20T13:43:42.667+0000] {processor.py:161} INFO - Started process (PID=2993) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:43:42.670+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:43:42.672+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:43:42.671+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:43:42.709+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:43:42.711+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:43:42.712+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:43:42.731+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:43:42.801+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:43:42.800+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:43:42.884+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:43:42.883+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:43:42.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.294 seconds
[2024-04-20T13:44:14.439+0000] {processor.py:161} INFO - Started process (PID=3007) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:44:14.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:44:14.443+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:44:14.442+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:44:14.472+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:44:14.473+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:44:14.474+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:44:14.494+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:44:14.552+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:44:14.551+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:44:14.605+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:44:14.604+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:44:14.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.231 seconds
[2024-04-20T13:44:45.539+0000] {processor.py:161} INFO - Started process (PID=3020) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:44:45.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:44:45.543+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:44:45.543+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:44:45.574+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:44:45.575+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:44:45.576+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:44:45.592+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:44:45.640+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:44:45.639+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:44:45.683+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:44:45.683+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:44:45.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.197 seconds
[2024-04-20T13:45:16.594+0000] {processor.py:161} INFO - Started process (PID=3034) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:45:16.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:45:16.597+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:45:16.597+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:45:16.623+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:45:16.623+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:45:16.624+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:45:16.636+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:45:16.670+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:45:16.670+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:45:16.703+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:45:16.702+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:45:16.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.154 seconds
[2024-04-20T13:45:47.455+0000] {processor.py:161} INFO - Started process (PID=3049) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:45:47.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:45:47.458+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:45:47.457+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:45:47.497+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:45:47.498+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:45:47.499+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:45:47.517+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:45:47.561+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:45:47.560+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:45:47.600+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:45:47.600+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:45:47.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.198 seconds
[2024-04-20T13:46:18.403+0000] {processor.py:161} INFO - Started process (PID=3063) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:46:18.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:46:18.406+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:46:18.406+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:46:18.434+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:46:18.435+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:46:18.436+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:46:18.453+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:46:18.522+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:46:18.521+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:46:18.584+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:46:18.584+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:46:18.629+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.236 seconds
[2024-04-20T13:46:49.657+0000] {processor.py:161} INFO - Started process (PID=3078) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:46:49.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:46:49.660+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:46:49.659+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:46:49.687+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:46:49.688+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:46:49.688+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:46:49.706+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:46:49.743+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:46:49.743+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:46:49.811+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:46:49.810+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:46:49.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.200 seconds
[2024-04-20T13:47:22.695+0000] {processor.py:161} INFO - Started process (PID=3092) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:47:22.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:47:22.701+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:47:22.700+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:47:22.753+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:47:22.775+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:47:22.778+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:47:22.830+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:47:22.885+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:47:22.885+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:47:22.944+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:47:22.944+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:47:22.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.318 seconds
[2024-04-20T13:47:54.562+0000] {processor.py:161} INFO - Started process (PID=3107) to work on /opt/airflow/dags/Prueba.py
[2024-04-20T13:47:54.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-20T13:47:54.567+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:47:54.566+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-20T13:47:54.606+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-20T13:47:54.607+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:47:54.608+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-20T13:47:54.634+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-20T13:47:54.753+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:47:54.752+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-20T13:47:54.822+0000] {logging_mixin.py:188} INFO - [2024-04-20T13:47:54.822+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-20T13:47:54.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.405 seconds
