[2024-04-17T00:03:17.113+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:03:17.115+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:03:17.147+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:03:17.145+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:03:17.338+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:03:17.554+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:03:18.050+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:03:18.349+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:03:20.650+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:03:20.649+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:03:21.708+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:03:21.707+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:03:23.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 6.299 seconds
[2024-04-17T00:03:58.148+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:03:58.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:03:58.211+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:03:58.210+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:03:59.729+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:03:59.759+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:03:59.763+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:03:59.841+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:04:00.056+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:04:00.056+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:04:00.312+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:04:00.312+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:04:00.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.644 seconds
[2024-04-17T00:04:32.548+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:04:32.565+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:04:32.576+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:04:32.568+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:04:33.025+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:04:33.029+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:04:33.039+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:04:33.162+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:04:33.595+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:04:33.594+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:04:33.845+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:04:33.844+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:04:33.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.454 seconds
[2024-04-17T00:05:11.607+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:05:11.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:05:11.636+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:05:11.635+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:05:12.117+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:05:12.173+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:05:12.190+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:05:12.304+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:05:13.115+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:05:13.114+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:05:13.293+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:05:13.293+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:05:14.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.721 seconds
[2024-04-17T00:05:49.849+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:05:49.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:05:49.936+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:05:49.935+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:06:04.598+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:06:04.634+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:06:04.916+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:06:05.055+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:06:05.488+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:06:05.488+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:06:05.710+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:06:05.710+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:06:17.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 27.445 seconds
[2024-04-17T00:06:47.601+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:06:47.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:06:47.617+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:06:47.616+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:06:47.715+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:06:47.739+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:06:47.747+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:06:47.800+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:06:47.949+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:06:47.948+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:06:48.064+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:06:48.063+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:06:48.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.574 seconds
[2024-04-17T00:07:18.549+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:07:18.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:07:18.563+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:07:18.562+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:07:18.712+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:07:18.715+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:07:18.718+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:07:18.758+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:07:18.837+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:07:18.837+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:07:18.901+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:07:18.901+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:07:19.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.048 seconds
[2024-04-17T00:07:50.230+0000] {processor.py:161} INFO - Started process (PID=153) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:07:50.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:07:50.244+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:07:50.243+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:07:50.674+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:07:50.675+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:07:50.676+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:07:50.709+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:07:50.891+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:07:50.890+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:07:50.981+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:07:50.981+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:07:53.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 3.040 seconds
[2024-04-17T00:08:27.566+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:08:27.568+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:08:27.571+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:08:27.571+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:08:30.118+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:08:30.120+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:08:30.121+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:08:30.203+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:08:31.369+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:08:31.367+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:08:31.823+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:08:31.822+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:08:34.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 6.917 seconds
[2024-04-17T00:09:05.466+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:09:05.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:09:05.725+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:09:05.479+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:09:05.916+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:09:05.917+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:09:05.918+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:09:06.742+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:09:07.367+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:09:07.367+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:09:08.401+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:09:08.400+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:09:09.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 3.575 seconds
[2024-04-17T00:09:39.611+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:09:39.614+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:09:39.620+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:09:39.619+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:09:39.660+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:09:39.662+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:09:39.663+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:09:39.689+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:09:39.769+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:09:39.768+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:09:39.817+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:09:39.816+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:09:39.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.348 seconds
[2024-04-17T00:10:11.047+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:10:11.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:10:11.064+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:10:11.063+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:10:11.316+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:10:11.317+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:10:11.318+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:10:11.361+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:10:11.550+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:10:11.549+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:10:11.732+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:10:11.731+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:10:12.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.032 seconds
[2024-04-17T00:10:43.399+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:10:43.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:10:43.430+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:10:43.429+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:10:43.824+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:10:43.835+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:10:43.837+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:10:43.888+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:10:43.992+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:10:43.991+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:10:44.152+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:10:44.152+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:10:44.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.861 seconds
[2024-04-17T00:11:14.805+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:11:14.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:11:14.809+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:11:14.808+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:11:15.112+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:11:15.139+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:11:15.141+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:11:15.168+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:11:15.253+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:11:15.252+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:11:15.294+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:11:15.294+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:11:16.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.690 seconds
[2024-04-17T00:11:47.030+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:11:47.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:11:47.034+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:11:47.034+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:11:47.063+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:11:47.064+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:11:47.065+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:11:47.077+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:11:47.110+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:11:47.110+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:11:47.150+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:11:47.149+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:11:47.886+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.864 seconds
[2024-04-17T00:12:18.969+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:12:18.971+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:12:18.974+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:12:18.974+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:12:18.996+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:12:18.997+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:12:18.997+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:12:19.008+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:12:19.042+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:12:19.042+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:12:19.073+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:12:19.072+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:12:19.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.802 seconds
[2024-04-17T00:12:50.321+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:12:50.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:12:50.338+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:12:50.337+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:12:50.440+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:12:50.440+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:12:50.442+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:12:50.488+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:12:50.608+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:12:50.608+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:12:50.691+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:12:50.691+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:12:50.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.511 seconds
[2024-04-17T00:13:20.931+0000] {processor.py:161} INFO - Started process (PID=269) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:13:20.933+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:13:20.935+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:13:20.935+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:13:20.964+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:13:20.965+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:13:20.966+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:13:20.978+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:13:21.016+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:13:21.016+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:13:21.074+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:13:21.073+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:13:21.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.272 seconds
[2024-04-17T00:13:51.355+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:13:51.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:13:51.359+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:13:51.359+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:13:51.396+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:13:51.397+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:13:51.398+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:13:51.414+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:13:51.461+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:13:51.460+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:13:51.507+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:13:51.506+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:13:51.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.202 seconds
[2024-04-17T00:14:21.857+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:14:21.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:14:21.861+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:14:21.860+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:14:21.893+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:14:21.894+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:14:21.895+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:14:21.916+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:14:21.971+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:14:21.970+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:14:22.021+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:14:22.021+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:14:22.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.034 seconds
[2024-04-17T00:14:53.099+0000] {processor.py:161} INFO - Started process (PID=302) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:14:53.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:14:53.104+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:14:53.103+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:14:53.133+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:14:53.133+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:14:53.134+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:14:53.147+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:14:53.187+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:14:53.187+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:14:53.248+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:14:53.247+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:14:53.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.196 seconds
[2024-04-17T00:15:23.505+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:15:23.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:15:23.514+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:15:23.513+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:15:23.566+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:15:23.567+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:15:23.568+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:15:23.609+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:15:23.738+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:15:23.737+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:15:23.870+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:15:23.869+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:15:24.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.570 seconds
[2024-04-17T00:15:54.215+0000] {processor.py:161} INFO - Started process (PID=323) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:15:54.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:15:54.221+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:15:54.220+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:15:54.250+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:15:54.250+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:15:54.251+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:15:54.264+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:15:54.306+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:15:54.306+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:15:54.371+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:15:54.370+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:15:54.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.302 seconds
[2024-04-17T00:16:24.735+0000] {processor.py:161} INFO - Started process (PID=334) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:16:24.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:16:24.744+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:16:24.743+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:16:24.804+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:16:24.805+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:16:24.806+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:16:24.819+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:16:24.878+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:16:24.876+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:16:24.924+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:16:24.923+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:16:25.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.576 seconds
[2024-04-17T00:16:55.507+0000] {processor.py:161} INFO - Started process (PID=345) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:16:55.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:16:55.521+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:16:55.520+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:16:55.570+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:16:55.571+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:16:55.573+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:16:55.603+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:16:55.642+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:16:55.642+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:16:55.677+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:16:55.677+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:16:55.867+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.391 seconds
[2024-04-17T00:17:26.462+0000] {processor.py:161} INFO - Started process (PID=355) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:17:26.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:17:26.467+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:17:26.466+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:17:26.498+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:17:26.499+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:17:26.500+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:17:26.516+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:17:26.577+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:17:26.574+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:17:26.650+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:17:26.650+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:17:26.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.276 seconds
[2024-04-17T00:17:57.504+0000] {processor.py:161} INFO - Started process (PID=366) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:17:57.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:17:57.513+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:17:57.512+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:17:57.565+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:17:57.566+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:17:57.567+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:17:57.596+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:17:57.655+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:17:57.654+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:17:57.735+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:17:57.735+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:17:57.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.300 seconds
[2024-04-17T00:18:28.150+0000] {processor.py:161} INFO - Started process (PID=377) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:18:28.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:18:28.161+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:18:28.159+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:18:28.201+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:18:28.202+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:18:28.203+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:18:28.224+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:18:28.274+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:18:28.273+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:18:28.327+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:18:28.327+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:18:28.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.235 seconds
[2024-04-17T00:18:58.860+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:18:58.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:18:58.866+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:18:58.866+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:18:58.889+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:18:58.890+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:18:58.891+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:18:58.902+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:18:58.936+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:18:58.935+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:18:58.968+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:18:58.968+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:18:59.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.273 seconds
[2024-04-17T00:19:29.689+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:19:29.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:19:29.695+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:19:29.694+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:19:29.814+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:19:29.815+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:19:29.816+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:19:29.851+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:19:29.916+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:19:29.916+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:19:29.965+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:19:29.965+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:19:30.773+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.101 seconds
[2024-04-17T00:20:01.006+0000] {processor.py:161} INFO - Started process (PID=410) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:20:01.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:20:01.016+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:20:01.015+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:20:01.201+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:20:01.205+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:20:01.210+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:20:01.237+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:20:01.370+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:20:01.369+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:20:01.462+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:20:01.462+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:20:01.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.534 seconds
[2024-04-17T00:20:32.258+0000] {processor.py:161} INFO - Started process (PID=422) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:20:32.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:20:32.636+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:20:32.635+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:20:33.249+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:20:33.251+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:20:33.252+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:20:33.279+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:20:33.330+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:20:33.330+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:20:33.381+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:20:33.380+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:20:34.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.663 seconds
[2024-04-17T00:21:06.891+0000] {processor.py:161} INFO - Started process (PID=433) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:21:07.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:21:07.350+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:21:07.349+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:21:09.162+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:21:09.174+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:21:09.175+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:21:09.226+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:21:09.346+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:21:09.345+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:21:09.503+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:21:09.503+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:21:09.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.844 seconds
[2024-04-17T00:21:40.596+0000] {processor.py:161} INFO - Started process (PID=444) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:21:40.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:21:40.601+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:21:40.600+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:21:40.633+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:21:40.634+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:21:40.634+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:21:40.648+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:21:40.707+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:21:40.707+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:21:40.899+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:21:40.898+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:21:41.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.461 seconds
[2024-04-17T00:22:19.044+0000] {processor.py:161} INFO - Started process (PID=455) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:22:19.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:22:19.115+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:22:19.108+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:22:20.977+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:22:21.011+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:22:21.071+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:22:23.676+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:22:24.732+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:22:24.731+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:22:25.077+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:22:25.077+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:22:31.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 12.408 seconds
[2024-04-17T00:23:02.703+0000] {processor.py:161} INFO - Started process (PID=472) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:23:02.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:23:02.709+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:23:02.709+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:23:02.756+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:23:02.757+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:23:02.758+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:23:03.494+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:23:03.787+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:23:03.787+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:23:04.093+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:23:04.091+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:23:04.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.632 seconds
[2024-04-17T00:23:34.573+0000] {processor.py:161} INFO - Started process (PID=483) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:23:34.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:23:34.578+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:23:34.577+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:23:34.645+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:23:34.661+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:23:34.662+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:23:34.688+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:23:34.777+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:23:34.777+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:23:34.849+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:23:34.848+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:23:35.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.506 seconds
[2024-04-17T00:24:05.403+0000] {processor.py:161} INFO - Started process (PID=494) to work on /opt/airflow/dags/Prueba.py
[2024-04-17T00:24:05.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-17T00:24:05.410+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:24:05.408+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-17T00:24:05.463+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-17T00:24:05.464+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:24:05.465+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-17T00:24:05.497+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-17T00:24:05.563+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:24:05.562+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-17T00:24:05.619+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:24:05.619+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-17T00:24:06.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.701 seconds
